-- Campos cadastrais em usuário e empresa
ALTER TABLE "Usuario" ADD COLUMN IF NOT EXISTS "telefone" TEXT;
ALTER TABLE "Usuario" ADD COLUMN IF NOT EXISTS "cargo" TEXT;
ALTER TABLE "Usuario" ADD COLUMN IF NOT EXISTS "observacoes" TEXT;

ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "cnpj" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "razaoSocial" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "nomeFantasia" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "emailContato" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "telefone" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "cep" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "logradouro" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "numero" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "complemento" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "bairro" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "cidade" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "uf" TEXT;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "observacoes" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Empresa_cnpj_key" ON "Empresa"("cnpj") WHERE "cnpj" IS NOT NULL;
